# Generated by Django 2.1 on 2018-10-16 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_text', models.CharField(max_length=150)),
                ('testing_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
