# Generated by Django 2.1 on 2018-10-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostmanClone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apiCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.TextField()),
                ('headersa1', models.TextField()),
                ('headersb1', models.TextField()),
                ('headersa2', models.TextField()),
                ('headersb2', models.TextField()),
                ('headersa3', models.TextField()),
                ('headersb3', models.TextField()),
            ],
        ),
    ]
