# Generated by Django 2.1 on 2018-10-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostmanClone', '0002_apicall'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='httpResponse',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
