# Generated by Django 2.1 on 2018-10-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostmanClone', '0003_apicall_httpresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicall',
            old_name='httpResponse',
            new_name='httpMethod',
        ),
    ]
