# Generated by Django 2.1 on 2018-10-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostmanClone', '0004_auto_20181018_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
